{
 "title": "marine-ledger-insurance",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Panel Title",
   "type": "graph",
   "gridPos": { "h": 19, "w": 19, "x": 2, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "broker_checkpointingRate",
     "select": [
      [
       { "params": [ "OneMinuteRate" ], "type": "field" }
      ]
     ]
    },
    {
     "measurement": "insurer_checkpointingRate",
     "select": [
      [
       { "params": [ "OneMinuteRate" ], "type": "field" }
      ]
     ]
    },
    {
     "measurement": "mnc_checkpointingRate",
     "select": [
      [
       { "params": [ "OneMinuteRate" ], "type": "field" }
      ]
     ]
    },
    {
     "measurement": "reinsurer_checkpointingRate",
     "select": [
      [
       { "params": [ "OneMinuteRate" ], "type": "field" }
      ]
     ]
    },
    {
     "measurement": "services_checkpointingRate",
     "select": [
      [
       { "params": [ "OneMinuteRate" ], "type": "field" }
      ]
     ]
    },
    {
     "measurement": "wholesaleBroker_checkpointingRate",
     "select": [
      [
       { "params": [ "OneMinuteRate" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "broker flows started/finished",
   "type": "graph",
   "gridPos": { "h": 9, "w": 19, "x": 2, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "broker_startedFlow",
     "select": [
      [
       { "params": [ "Count" ], "type": "field" }
      ]
     ]
    },
    {
     "measurement": "broker_finishedFlow",
     "select": [
      [
       { "params": [ "Count" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "insurer flows started/finished",
   "type": "graph",
   "gridPos": { "h": 9, "w": 19, "x": 2, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "insurer_startedFlow",
     "select": [
      [
       { "params": [ "Count" ], "type": "field" }
      ]
     ]
    },
    {
     "measurement": "insurer_finishedFlow",
     "select": [
      [
       { "params": [ "Count" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "mnc flows started/finished",
   "type": "graph",
   "gridPos": { "h": 10, "w": 19, "x": 2, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "mnc_startedFlow",
     "select": [
      [
       { "params": [ "Count" ], "type": "field" }
      ]
     ]
    },
    {
     "measurement": "mnc_finishedFlow",
     "select": [
      [
       { "params": [ "Count" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "reinsurer flows started/finished",
   "type": "graph",
   "gridPos": { "h": 10, "w": 19, "x": 2, "y": 47 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "reinsurer_startedFlow",
     "select": [
      [
       { "params": [ "Count" ], "type": "field" }
      ]
     ]
    },
    {
     "measurement": "reinsurer_finishedFlow",
     "select": [
      [
       { "params": [ "Count" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "services flows started/finished",
   "type": "graph",
   "gridPos": { "h": 10, "w": 19, "x": 2, "y": 57 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "services_startedFlow",
     "select": [
      [
       { "params": [ "Count" ], "type": "field" }
      ]
     ]
    },
    {
     "measurement": "services_finishedFlow",
     "select": [
      [
       { "params": [ "Count" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "wholesaleBroker flows started/finished",
   "type": "graph",
   "gridPos": { "h": 10, "w": 19, "x": 2, "y": 67 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "wholesaleBroker_startedFlow",
     "select": [
      [
       { "params": [ "Count" ], "type": "field" }
      ]
     ]
    },
    {
     "measurement": "wholesaleBroker_finishedFlow",
     "select": [
      [
       { "params": [ "Count" ], "type": "field" }
      ]
     ]
    }
   ]
  }
 ]
}